# Window Customization
window:
  dimensions:
    columns: 100
    lines: 40
  padding:
    x: 15
    y: 15
scrolling:
  history: 10000
  multiplier: 3
dynamic_title: true

# Font Customization
font:
  normal:
    family: Inconsolata for Powerline
    style: Regular
  bold:
    family: Inconsolata for Powerline
    style: Bold
  italic:
    family: Inconsolata for Powerline
    style: Italic
  size: 15
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: false
  debug:
    persistent_logging: false
draw_bold_text_with_bright_colors: true

# Color Settings (Gruvbox)
colors:
  primary:
    background: "#212121"
    foreground: "#ebdbb2"

  normal:
    black: "#282828"
    red: "#cc241d"
    green: "#98971a"
    yellow: "#d79921"
    blue: "#458588"
    magenta: "#b16286"
    cyan: "#689d6a"
    white: "#a89984"

  bright:
    black: "#928374"
    red: "#fb4934"
    green: "#b8bb26"
    yellow: "#fabd2f"
    blue: "#83a598"
    magenta: "#d3869b"
    cyan: "#8ec07c"
    white: "#ebdbb2"

  selection:
    text: "0xffffff"
    background: "0xdc3232"
    white: "0xffffff"
cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
  - { key: N, mods: Control, action: SpawnNewInstance }
